### ISSUE TITLE
Windows 7 & Trezord 1.1.3 + update = very slowly update in 90% times

### ISSUE THREAD

**Issue by Perlover** [trezor/trezord#23]
Hi,
I tried other USB cables, i installed 1.1.2 bridge version, i changed trust level in KIS 13.* to trusted for trezord process (your exe file signed by expired signature)...

I have 5 trezors for experiments. And all devices very slowly updated (i could not wait update because i wait 5 minutes and disconnect devices) in 90% cases... I stopped and run trezord again. Nothing helps. In 10% cases update in site mytrezor.com works fine.

I didn't find this problem in internet. But i think it can be there... I cannot atach even log because update process doesn't allow to me copy correct log file from log icon...

**Comment by Perlover** [comment]
I think there only one way - if after message about update with button "Yes, update" if i click this button and very very quickly (<0.1 sec) i click "Confirm" soft button - i can start update process. Else i have infinity update process...

**Comment by runn1ng** [comment]
Hey, we are trying to solve this.

Please try to use chrome extension with chrome or chromium in the meantime.

**Comment by jhoenicke** [comment]
I think I know a possible reason.  The usb stack of libopencm3 gets easily out of sync when a usb message is not immediately polled.  I have an open pull request for this.  For normal firmware behaviour this is mostly fixed now by using `usbDelay` instead of `delay`, which polls the usb port.  But the bootloader doesn't do it.

The only workaround (since we can't change the bootloader) is to not send any message while the device is waiting for a button press.  Especially don't reenumerate the usb ports, since this will flood the device with control messages.

Related to trezor/trezor-mcu#98.

**Comment by runn1ng** [comment]
This might be related to this issue

https://github.com/trezor/trezord/issues/27

**Comment by runn1ng** [comment]
Can you try the version from master if it's fixed? ( @Perlover I sent you binary with built installator to e-mail)

**Comment by runn1ng** [comment]
should be now fixed on master & in released version (now on mytrezor). Closing, please tell me if it's still hapenning

**Comment by slush0** [comment]
We're talking about Bridge 1.2.0 which was publicly released less than hour ago.
