### ISSUE TITLE
Fedora 25 rpm install fails

### ISSUE THREAD

**Issue by ricco386** [trezor/trezord#40]
Download and install of the `trezor-bridge-1.2.1-1.x86_64.rpm` package fails:

```
error: Failed dependencies:
	libmicrohttpd.so.10()(64bit) is needed by trezor-bridge-1.2.1-1.x86_64
```

**Comment by saleemrashid** [comment]
@ricco386 What command are you using to install the RPM?

**Comment by prusnak** [comment]
Known issue. Distro does not ship libmicrohttpd10 package and I am hesitant to upgrade the dependency to libmicrohttpd10 because of older/enterprise RPM distros. Workaround: build from source.

**Comment by ricco386** [comment]
@saleemrashid I did standard fedora way: `sudo dnf install trezor-bridge-1.2.1-1.x86_64.rpm`

@prusnak thanks. Strange thing is that in the fedora (updates) repository there is libmicrohttpd package that I can install but it does not provide libmicrohttpd.so :( anyway, not a problem to build from source, may  be just leave a note on website when downloading rpm file...

**Comment by clayt0nk** [comment]
dpkg -i trezor-bridge_1.2.1_amd64.deb 

is also failing on current Debian because libmicrohttpd10 is not available, only libmicrohttpd12. Note that this is also true for the latest / just-released Debian Stable, "Stretch".

Local source build, after much hair-pulling figuring out missing dependencies, also fails:

[ 91%] Building CXX object CMakeFiles/trezord.dir/src/main.cpp.o
[ 91%] Building CXX object CMakeFiles/trezord.dir/src/config/config.pb.cc.o
In file included from /usr/local/src/trezord/src/config/config.pb.cc:5:0:
/usr/local/src/trezord/src/config/config.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/usr/local/src/trezord/src/config/config.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/usr/local/src/trezord/src/config/config.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~

This machine is a fairly recent install, there should not be stray versions of protobuf laying around the file system. This should be it:

# wajig list-installed | grep protobuf
libprotobuf-c1:amd64
libprotobuf-dev:amd64
libprotobuf-lite10:amd64
libprotobuf10:amd64
python-protobuf

This is beginning to put me off. I only have a few days to decide whether or not I will return the device.

**Comment by runn1ng** [comment]
Can't we link libmicrohttpd statically so we don't have to care about this crap?

**Comment by prusnak** [comment]
We could, but nobody was able to do this. I tried (at least three times) and failed. libmicrohttpd wants gnutls and I had really big trouble linking that statically. (and you don't want to link gnutls dynamically, because they change sonames every few weeks)

**Comment by prusnak** [comment]
@clayt0nk change directory into `src/config` and run the following to regenerate protobuf files to your protobuf version:

```
wget https://raw.githubusercontent.com/trezor/trezor-common/master/protob/config.proto
protoc -I/usr/include -I. --cpp_out=. config.proto
```

After that you should be able to run local build.

**Comment by clayt0nk** [comment]
Thanks, the build finishes without error now.

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/trezord/build
[  8%] Built target hidapi
[ 82%] Built target TrezorCrypto
Scanning dependencies of target trezord
[ 86%] Building CXX object CMakeFiles/trezord.dir/src/config/config.pb.cc.o
[ 91%] Building CXX object CMakeFiles/trezord.dir/src/main.cpp.o
[ 95%] Linking CXX executable trezord
[100%] Built target trezord

(Note: add an "apt-get install protobuf-compiler" to above instructions.)
I am not seeing a new .deb. Is the product of the build trezord/build/trezord,
or is there another step to generate a package?

**Comment by prusnak** [comment]
You can use `trezord/build/trezord` directly.

**Comment by clayt0nk** [comment]
Ok, I get it, trezord is just a bit of glue allowing your web application at https://wallet.trezor.io/ to talk to the local Trezor device. This is not at all clear from the docs, a bit of architectural explanation would be very helpful here. At the moment everything is working.

But, it seems trezord is perhaps an indispensable bit of glue, since the Chrome plugin contains only minimal functionality. Unless the Android app (not yet seen, waiting on cable delivery) is a drop-in replacement? I hope so, because there is also the issue of living somewhere (like here in China) where network quality and level of censorship can be highly variable. Relying on a very remote network connection to use my hardware wallet in China makes me just a wee bit queasy.

**Comment by prusnak** [comment]
Chrome Extension provides every functionality of the Bridge and is the recommended option actually. It is not inferior to Bridge.
If you feel documentation is lacking some info, I would love to merge some changes of yours, because I am blind to missing things in docu (as I've been using TREZOR every day for 3 years already).

**Comment by clayt0nk** [comment]
Web wallet continues to behave.

Re. Chrome Extension (ver. 1.2.5 on Chromium Version 59.0.3071.104 (Developer Build) built on Debian 9.0, running on Debian buster/sid (64-bit)

I am seeing a small fraction of web wallet functionality (see screenshot). If I click on the "go to Trezor wallet" link it goes to wallet.trezor.io in Firefox.

![screenshot from 2017-07-15 17-40-57](https://user-images.githubusercontent.com/3198617/28238375-d1aa3c3e-6984-11e7-9039-5fb66116b51b.png)

**Comment by prusnak** [comment]
Yes, that is what I meant, sorry for confusion. I tend to forget that extension contains also some UI functionality, which is indeed minimalistic when compared to real wallet.

Anyway, let's not discuss here anymore as this is getting really offtopic. As you learnt in another thread, source to documentation is here: https://github.com/satoshilabs/docs and any improvements are really really welcome! Also feel free to file issues there if you want to clarify some stuff

**Comment by zufanka** [comment]
Also on Fedora (26). Problem is the same. On top of that I fail to be able to use the chrome extension.
See log below

> ["log","Sat, 23 Sep 2017 16:44:22 GMT","[app] User agent : ","Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36"]
> ["log","Sat, 23 Sep 2017 16:44:22 GMT","[trezor] Attempting to load Chrome Extension transport at","jcjjhjgimijdkoamemaghajlhegmoclj"]
> ["log","Sat, 23 Sep 2017 16:44:22 GMT","[trezor] Loaded Chrome Extension transport"]
> ["error","Sat, 23 Sep 2017 16:45:27 GMT","[trezor] Error received",{"type":"error","message":"Failed to open HID device."}]
> ["log","Sat, 23 Sep 2017 16:45:27 GMT","[deviceList] Catched error, printing stack"]
> ["log","Sat, 23 Sep 2017 16:45:27 GMT",{}]
> ["log","Sat, 23 Sep 2017 16:45:27 GMT","Error: Failed to open HID device.\n    at e (chrome-extension://jcjjhjgimijdkoamemaghajlhegmoclj/management/scripts/c82fa6b3.libs.js:23:11489)\n    at sendResponseAndClearCallback (extensions::messaging:417:9)\n    at messageListener (extensions::messaging:449:11)\n    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)\n    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:140:26)\n    at EventImpl.dispatch_ (extensions::event_bindings:387:35)\n    at EventImpl.dispatch (extensions::event_bindings:409:17)\n    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:140:26)\n    at dispatchOnMessage (extensions::messaging:390:22)"]

**Comment by clayt0nk** [comment]
The only time the Chrome extension does not work for me (on Debian) is when I run it behind firejail. (I believe firejail limits Chromium access to the file system, to ~/Downloads only.) Are you perhaps running SELinux ro Apparmor, which could be doing something similar?

**Comment by zufanka** [comment]
@clayt0nk yes, SELinux is enabled on my system. How do I fix it?

**Comment by clayt0nk** [comment]
@zufanka  I would first disable it and test to see if that makes your problem go away. If so, you then have three options:
* leave it disabled
* disable it when you use Trezor, and then re-enable it
* modify SELinux's chromium profile to let Trezor work

Note that the last option is probably quite non-trivial if you are not already familiar with SELinux. That said, I am sure the SELinux people would be very happy to receive a patch that makes SELinux better.

**Comment by prusnak** [comment]
I have just very vague experience with SELinux. There is a tool called [audit2allow](https://fedoraproject.org/wiki/SELinux/audit2allow) which can generate a policy from series of denied operations. I would recommend to try this to figure out what needs to be enabled in order to get TREZOR working. My guess is that SELinux blocks Chromium from accessing HID USB devices.

Maybe @lkundrak can help with that? :wink:

**Comment by saleemrashid** [comment]
@zufanka Could you post the output of `dmesg | grep avc:`?

**Comment by zufanka** [comment]
@saleemrashid I get nothing :/

**Comment by saleemrashid** [comment]
@zufanka Have you tried running `setenforce 0` before running Chrome? Does that fix the problem?

**Comment by zufanka** [comment]
@saleemrashid 
I did setenforce 0 and restarted chrome. It did not help. Still have the same error.
I do have an udev management tool installed. What do I need to set up?

**Comment by saleemrashid** [comment]
@zufanka 

1. Download [this file](https://github.com/trezor/trezor-common/blob/master/udev/51-trezor.rules) to `/etc/udev/rules.d/51-trezor.rules`

2. Run `udevadm control --reload-rules` to load the new rules

3. Disconnect (if it is connected) and reconnect the TREZOR (or use `udevadm trigger`)

**Comment by zufanka** [comment]
@saleemrashid it works, thank you very much!
Could you however please very simply explain what did I just do?

**Comment by AloisMahdal** [comment]
Is there any perspective as to when this is going to be fixed?

BTW I tried to build from source on Fedora 26 and failed for reasons I don't understand.

Anyway I don't think every Trezor user should be also a C/C++/boost/whatever... developer, so having working deb/rpm packages at least for "big" distros would be "nice" (as in "I don't feel like I spent EUR130 for a wonderful device I can't use").

**Comment by AloisMahdal** [comment]
Workaround: I just created **unofficial** build at [my Fedora COPR repo][1].  So far I've only enabled Fedora 25-27 on x86_64; let me know (see contact page on the COPR project) if you need other builds.

**Comment by kargakis** [comment]
@AloisMahdal thanks for those builds! 

> Anyway I don't think every Trezor user should be also a C/C++/boost/whatever... developer, so having working deb/rpm packages at least for "big" distros would be "nice" (as in "I don't feel like I spent EUR130 for a wonderful device I can't use").

Totally agree. 

I failed to build both locally and via docker on F26 (https://github.com/trezor/trezord/issues/59).

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

Try compiling and using that one. If you find issues, please report them to that repository. Thank you!
