### ISSUE TITLE
Protocol version auto-detection is broken

### ISSUE THREAD

**Issue by alexdupre** [trezor/trezord#53]
I don't know how the V2 protocol should work, but the `try_hid_version` function seems broken, at least on a few platforms.
My understanding is that the check is done by writing 65 bytes instead of 64, adding a leading null byte, and verifying that 65 bytes are written.
But the `hid_write` function when it sees a leading 0x00 byte, removes it and then increases the returned length by 1, so the two version checks produce exactly the same write of 64 bytes on the wire, while the returned number is artificially altered for the V2 check.

```
        int report_number = data[0];
        int skipped_report_id = 0;

        if (report_number == 0x0) {
                data++;
                length--;
                skipped_report_id = 1;
        }

        ...

        if (skipped_report_id)
                actual_length++;

        return actual_length;
```

**Comment by prusnak** [comment]
You are mixing two things. `trezord` cannot yet speak TREZORv2 protocol.

What you are seeing are two different HID implementations we are using for TREZORv1. The older, used report number 63 with 63 bytes of data attached. The newer uses no report number with 64 bytes of data attached, where the first byte is `0x3F` == `63` ==  `?`. This produces the same behavior on Linux systems, but not on Windows, that's why we need to detect with version works.
